export const networks = ["SOLANA", "SUI", "ETH", "BNB", "TRON"] as const;
export type Network = typeof networks[number];

export const packagesData: Record<
  Network,
  {
    name: string;
    price: string;
    desc: string;
    features: string[];
  }[]
> = {
  SOLANA: [
    {
      name: "Paket Dasar",
      price: "$2.000",
      desc: "Fitur penting untuk membuat token dasar.",
      features: [
        "Pembuatan token di jaringan SOLANA",
        "Kon Paskoin 1M",
        "Tambahkan Likuiditas $50 USD",
        "Media Sosial (Twitter)",
        "Telegram (5 anggota)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Efek Lainnya",
      ],
    },
    {
      name: "Paket Standar",
      price: "$2.000",
      desc: "Fitur penting untuk membuat token standar.",
      features: [
        "Pembuatan token di jaringan SOLANA",
        "Kon Paskoin 5M",
        "Tambahkan Likuiditas $75 USD",
        "Media Sosial (Twitter)",
        "Telegram (50 anggota)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Efek Lainnya",
        "2 postingan pertama untuk promosi",
      ],
    },
    {
      name: "Paket Lanjutan",
      price: "$2.000",
      desc: "Fitur penting untuk membuat token canggih.",
      features: [
        "Pembuatan token di jaringan SOLANA",
        "Kon Paskoin 10M",
        "Tambahkan Likuiditas $100 USD",
        "Media Sosial (Twitter, Telegram 100 anggota)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Efek Lainnya",
        "10 postingan pertama untuk promosi",
        "Pencatatan Eksekutif NusaDex dan Bursa Efek Lainnya",
      ],
    },
  ],

  SUI: [
    {
      name: "Basic Package",
      price: "$1.500",
      desc: "Essential features for creating a basic token.",
      features: [
        "Token creation on the SUI network",
        "Supply Coin 1M",
        "Add Liquidity $30 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
      ],
    },
    {
      name: "Standard Package ",
      price: "$3.000",
      desc: "Essential features for creating a standard token.",
      features: [
        "Token creation on the SUI network",
        "Supply Coin 5M",
        "Add Liquidity $50 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 3 posts for promotion",
      ],
    },
    {
      name: "Advance Package",
      price: "$4.500",
      desc: "Essential features for creating an advance token.",
      features: [
        "Token creation on the SUI network",
        "Supply Coin 10M",
        "Add Liquidity $75 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 10 posts for promotion",
        "Exclusive Listing of NusaDex and other Exchanges",
        "Additional features such as:",
        "Social Media X Verified",
        "Request custom Supply",
        "50 Wallet Holder",
      ],
    },
  ],

  ETH: [
    {
      name: "Basic Package",
      price: "$12.500",
      desc: "Essential features for creating a basic token.",
      features: [
        "Token creation on the ETHEREUM network",
        "Supply Coin 1M",
        "Add Liquidity $70 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
      ],
    },
    {
      name: "Standard Package ",
      price: "$37.000",
      desc: "Essential features for creating a standard token.",
      features: [
        "Token creation on the ETHEREUM network",
        "Supply Coin 5M",
        "Add Liquidity $100 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 3 posts for promotion",
      ],
    },
    {
      name: "Advance Package",
      price: "$74.000",
      desc: "Essential features for creating an advance token.",
      features: [
        "Token creation on the ETHEREUM network",
        "Supply Coin 10M",
        "Add Liquidity $130 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 10 posts for promotion",
        "Exclusive Listing of NusaDex and other Exchanges",
        "Additional features such as:",
        "Social Media X Verified",
        "Request custom Supply",
        "50 Wallet Holder",
      ],
    },
  ],

  BNB: [
    {
      name: "Basic Package",
      price: "$4.500",
      desc: "Essential features for creating a basic token.",
      features: [
        "Token creation on the BNB network",
        "Supply Coin 1M",
        "Add Liquidity $50 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
      ],
    },
    {
      name: "Standard Package ",
      price: "$9.000",
      desc: "Essential features for creating a standard token.",
      features: [
        "Token creation on the BNB network",
        "Supply Coin 5M",
        "Add Liquidity $75 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 3 posts for promotion",
      ],
    },
    {
      name: "Advance Package",
      price: "$12.500",
      desc: "Essential features for creating an advance token.",
      features: [
        "Token creation on the BNB network",
        "Supply Coin 10M",
        "Add Liquidity $100 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 10 posts for promotion",
        "Exclusive Listing of NusaDex and other Exchanges",
        "Additional features such as:",
        "Social Media X Verified",
        "Request custom Supply",
        "50 Wallet Holder",
      ],
    },
  ],

  TRON: [
    {
      name: "Basic Package",
      price: "$4.000",
      desc: "Essential features for creating a basic token.",
      features: [
        "Token creation on the TRON network",
        "Supply Coin 1M",
        "Add Liquidity $50 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
      ],
    },
    {
      name: "Standard Package ",
      price: "$7.000",
      desc: "Essential features for creating a standard token.",
      features: [
        "Token creation on the TRON network",
        "Supply Coin 5M",
        "Add Liquidity $75 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 3 posts for promotion",
      ],
    },
    {
      name: "Advance Package",
      price: "$9.500",
      desc: "Essential features for creating an advance token.",
      features: [
        "Token creation on the TRON network",
        "Supply Coin 10M",
        "Add Liquidity $100 USD",
        "Social Media (X/Twitter, Telegram, and Instagram)",
        "Website + Free Domain 1 Year",
        "Manual Book",
        "Whitepaper & Roadmap",
        "NusaDex & Other Exchange Listings",
        "First 10 posts for promotion",
        "Exclusive Listing of NusaDex and other Exchanges",
        "Additional features such as:",
        "Social Media X Verified",
      ],
    },
  ],
};