export const networks = ["SOLANA", "SUI", "ETH", "BNB", "TRON"] as const;
export type Network = typeof networks[number];

export const packagesData: Record<
  Network,
  {
    name: string;
    price: string;
    desc: string;
    features: string[];
  }[]
> = {
  SOLANA: [
    {
      name: "Paket Dasar",
      price: "$2,000",
      desc: "Fitur penting untuk membuat token dasar.",
      features: [
        "Pembuatan token di jaringan SOLANA",
        "Supply Koin 1 Juta",
        "Tambahkan Likuiditas $50 USD",
        "Media Sosial (X/Twitter)",
        "Telegram (5 anggota)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
      ],
    },
    {
      name: "Paket Standar",
      price: "$4,000",
      desc: "Fitur penting untuk membuat token standar.",
      features: [
        "Pembuatan token di jaringan SOLANA",
        "Supply Koin 5 Juta",
        "Tambahkan Likuiditas $75 USD",
        "Media Sosial (X/Twitter)",
        "Telegram (50 anggota)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "2 postingan pertama untuk promosi",
      ],
    },
    {
      name: "Paket Lanjutan",
      price: "$6,500",
      desc: "Fitur penting untuk membuat token canggih.",
      features: [
        "Pembuatan token di jaringan SOLANA",
        "Supply Koin 10 Juta",
        "Tambahkan Likuiditas $100 USD",
        "Media Sosial (X/Twitter, Telegram 100 anggota)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "10 postingan pertama untuk promosi",
        "Pencatatan eksklusif di NusaDex dan Bursa lainnya",
      ],
    },
  ],

  SUI: [
    {
      name: "Paket Dasar",
      price: "$1,500",
      desc: "Fitur penting untuk membuat token dasar.",
      features: [
        "Pembuatan token di jaringan SUI",
        "Supply Koin 1 Juta",
        "Tambahkan Likuiditas $30 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
      ],
    },
    {
      name: "Paket Standar",
      price: "$3,000",
      desc: "Fitur penting untuk membuat token standar.",
      features: [
        "Pembuatan token di jaringan SUI",
        "Supply Koin 5 Juta",
        "Tambahkan Likuiditas $50 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "3 postingan pertama untuk promosi",
      ],
    },
    {
      name: "Paket Lanjutan",
      price: "$4,500",
      desc: "Fitur penting untuk membuat token canggih.",
      features: [
        "Pembuatan token di jaringan SUI",
        "Supply Koin 10 Juta",
        "Tambahkan Likuiditas $75 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "10 postingan pertama untuk promosi",
        "Pencatatan eksklusif di NusaDex dan Bursa lainnya",
        "Media Sosial X Terverifikasi",
        "Permintaan Supply khusus",
        "50 Pemegang Dompet",
      ],
    },
  ],

  ETH: [
    {
      name: "Paket Dasar",
      price: "$12,500",
      desc: "Fitur penting untuk membuat token dasar.",
      features: [
        "Pembuatan token di jaringan ETHEREUM",
        "Supply Koin 1 Juta",
        "Tambahkan Likuiditas $70 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
      ],
    },
    {
      name: "Paket Standar",
      price: "$37,000",
      desc: "Fitur penting untuk membuat token standar.",
      features: [
        "Pembuatan token di jaringan ETHEREUM",
        "Supply Koin 5 Juta",
        "Tambahkan Likuiditas $100 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "3 postingan pertama untuk promosi",
      ],
    },
    {
      name: "Paket Lanjutan",
      price: "$74,000",
      desc: "Fitur penting untuk membuat token canggih.",
      features: [
        "Pembuatan token di jaringan ETHEREUM",
        "Supply Koin 10 Juta",
        "Tambahkan Likuiditas $130 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "10 postingan pertama untuk promosi",
        "Pencatatan eksklusif di NusaDex dan Bursa lainnya",
        "Media Sosial X Terverifikasi",
        "Permintaan Supply khusus",
        "50 Pemegang Dompet",
      ],
    },
  ],

  BNB: [
    {
      name: "Paket Dasar",
      price: "$4,500",
      desc: "Fitur penting untuk membuat token dasar.",
      features: [
        "Pembuatan token di jaringan BNB",
        "Supply Koin 1 Juta",
        "Tambahkan Likuiditas $50 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
      ],
    },
    {
      name: "Paket Standar",
      price: "$9,000",
      desc: "Fitur penting untuk membuat token standar.",
      features: [
        "Pembuatan token di jaringan BNB",
        "Supply Koin 5 Juta",
        "Tambahkan Likuiditas $75 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "3 postingan pertama untuk promosi",
      ],
    },
    {
      name: "Paket Lanjutan",
      price: "$12,500",
      desc: "Fitur penting untuk membuat token canggih.",
      features: [
        "Pembuatan token di jaringan BNB",
        "Supply Koin 10 Juta",
        "Tambahkan Likuiditas $100 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "10 postingan pertama untuk promosi",
        "Pencatatan eksklusif di NusaDex dan Bursa lainnya",
        "Media Sosial X Terverifikasi",
        "Permintaan Supply khusus",
        "50 Pemegang Dompet",
      ],
    },
  ],

  TRON: [
    {
      name: "Paket Dasar",
      price: "$4,000",
      desc: "Fitur penting untuk membuat token dasar.",
      features: [
        "Pembuatan token di jaringan TRON",
        "Supply Koin 1 Juta",
        "Tambahkan Likuiditas $50 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
      ],
    },
    {
      name: "Paket Standar",
      price: "$7,000",
      desc: "Fitur penting untuk membuat token standar.",
      features: [
        "Pembuatan token di jaringan TRON",
        "Supply Koin 5 Juta",
        "Tambahkan Likuiditas $75 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "3 postingan pertama untuk promosi",
      ],
    },
    {
      name: "Paket Lanjutan",
      price: "$9,500",
      desc: "Fitur penting untuk membuat token canggih.",
      features: [
        "Pembuatan token di jaringan TRON",
        "Supply Koin 10 Juta",
        "Tambahkan Likuiditas $100 USD",
        "Media Sosial (X/Twitter, Telegram, dan Instagram)",
        "Situs Web + Domain Gratis 1 Tahun",
        "Buku Manual",
        "Buku Putih & Peta Jalan",
        "Daftar NusaDex & Bursa Lainnya",
        "10 postingan pertama untuk promosi",
        "Pencatatan eksklusif di NusaDex dan Bursa lainnya",
        "Media Sosial X Terverifikasi",
      ],
    },
  ],
};
